language: dart

dart:
  - stable

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-warnings .

cache:
  directories:
    - $HOME/.pub-cache

# Only build pull requests targeting master
branches:
  only:
    master
