name: tintin
version: 1.0.0
description: A declarative authorization library for Dart.
homepage: https://github.com/fkleon/tintin

dependencies:
  collection: ^1.14.11

dev_dependencies:
  test: ^1.0.0

environment:
  sdk: ">=2.12.0 <4.0.0"
