name: tintin
version: 0.1.0+2
author: Frederik Leonhardt <frederik.leonhardt@gmail.com>
description: A declarative authorization library for Dart.
homepage: https://github.com/fkleon/tintin
dependencies:
  collection: ^1.14.11
dev_dependencies:
  test: ^1.0.0
environment:
  sdk: ^2.0.0
